[package]
name = "jinx-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "jinx_core"

[dependencies]
serde = { workspace = true }
regex-lite = { workspace = true }
thiserror = { workspace = true }
rusqlite = { workspace = true }
directories = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
