//! IPC envelope and payload types for the Canal_IPC between the Rust TUI
//! and the Python Agent.
//!
//! The on-the-wire format is JSON Lines: one JSON object per line,
//! UTF-8 encoded, terminated with `\n`. Every message follows the common
//! envelope described in `design.md` → Canal_IPC and Data Models:
//!
//! ```jsonc
//! {
//!   "v": 1,
//!   "id": "d3f4c1e6-...",          // UUIDv4 generated by the sender
//!   "kind": "request" | "response" | "event",
//!   "type": "user_message" | "agent_reply" | "storage.create_task" | ...,
//!   "payload": { ... } | null,      // type-specific body, omitted on error responses
//!   "ref":   "...",                 // id of the request this response refers to
//!   "error": { "code": "...", "message": "..." }
//! }
//! ```
//!
//! Only `v = 1` is accepted: deserializing an envelope with any other
//! protocol version yields a clear serde error.
//!
//! # Design choices
//!
//! * The envelope holds `payload` as `Option<serde_json::Value>`; typed
//!   payload structs (`UserMessagePayload`, `StorageCreateTaskRequest`, …)
//!   are defined per message `type` and converted with
//!   [`Envelope::payload_as`] / [`Envelope::with_payload`]. This keeps
//!   error responses (no payload) and progress events (open shape) easy
//!   to represent without a giant tagged enum.
//! * Data-model-level DTOs (`StorageTaskDto`, `StorageEventDto`,
//!   `StorageGroupDto`) are defined here in the `tui` crate to avoid
//!   coupling the IPC layer to the `storage` crate, which is implemented
//!   in later spec tasks.

use serde::{Deserialize, Deserializer, Serialize};
use uuid::Uuid;

// ---------------------------------------------------------------------------
// Envelope
// ---------------------------------------------------------------------------

/// Current version of the Canal_IPC envelope schema. Bumped for any
/// backward-incompatible change.
pub const PROTOCOL_VERSION: u8 = 1;

/// Common envelope exchanged between the TUI and the Agent on every line
/// of the Canal_IPC.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Envelope {
    /// Protocol version. Always [`PROTOCOL_VERSION`] (`1`) on the wire.
    #[serde(deserialize_with = "deserialize_protocol_version")]
    pub v: u8,

    /// UUIDv4 of this message, generated by the sender.
    pub id: Uuid,

    /// Whether this is a request, response or one-way event.
    pub kind: Kind,

    /// Concrete message type (`user_message`, `storage.create_task`, …).
    #[serde(rename = "type")]
    pub message_type: MessageType,

    /// Type-specific payload. Absent on error responses.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payload: Option<serde_json::Value>,

    /// `id` of the request this response/event refers to, when applicable.
    #[serde(default, rename = "ref", skip_serializing_if = "Option::is_none")]
    pub ref_id: Option<Uuid>,

    /// Error payload when `kind = response` and the operation failed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<StorageError>,
}

/// Custom deserialization for the `v` field: only `1` is accepted.
fn deserialize_protocol_version<'de, D>(deserializer: D) -> Result<u8, D::Error>
where
    D: Deserializer<'de>,
{
    use serde::de::Error as _;
    let v = u8::deserialize(deserializer)?;
    if v != PROTOCOL_VERSION {
        return Err(D::Error::custom(format!(
            "unsupported IPC protocol version: expected {}, got {}",
            PROTOCOL_VERSION, v
        )));
    }
    Ok(v)
}

impl Envelope {
    /// Build a new envelope with a freshly generated UUIDv4 and a typed
    /// payload serialized to `serde_json::Value`.
    pub fn new<P: Serialize>(
        kind: Kind,
        message_type: MessageType,
        payload: &P,
    ) -> Result<Self, serde_json::Error> {
        Ok(Self {
            v: PROTOCOL_VERSION,
            id: Uuid::new_v4(),
            kind,
            message_type,
            payload: Some(serde_json::to_value(payload)?),
            ref_id: None,
            error: None,
        })
    }

    /// Build an envelope with no payload (e.g. `shutdown` requests or
    /// error responses).
    pub fn new_empty(kind: Kind, message_type: MessageType) -> Self {
        Self {
            v: PROTOCOL_VERSION,
            id: Uuid::new_v4(),
            kind,
            message_type,
            payload: None,
            ref_id: None,
            error: None,
        }
    }

    /// Set `ref_id` in the builder style.
    pub fn with_ref(mut self, ref_id: Uuid) -> Self {
        self.ref_id = Some(ref_id);
        self
    }

    /// Replace `payload` with a serialized typed value, in the builder style.
    pub fn with_payload<P: Serialize>(mut self, payload: &P) -> Result<Self, serde_json::Error> {
        self.payload = Some(serde_json::to_value(payload)?);
        Ok(self)
    }

    /// Attach an error in the builder style. Clears the payload since
    /// error responses carry no payload.
    pub fn with_error(mut self, error: StorageError) -> Self {
        self.payload = None;
        self.error = Some(error);
        self
    }

    /// Try to parse the `payload` as a typed value.
    ///
    /// Returns `Ok(None)` if no payload is present and `Ok(Some(payload))`
    /// on successful decoding.
    pub fn payload_as<P: for<'de> Deserialize<'de>>(
        &self,
    ) -> Result<Option<P>, serde_json::Error> {
        match &self.payload {
            Some(value) => Ok(Some(serde_json::from_value(value.clone())?)),
            None => Ok(None),
        }
    }
}

// ---------------------------------------------------------------------------
// Kind and MessageType
// ---------------------------------------------------------------------------

/// Whether an envelope carries a request, a response or a one-way event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Kind {
    Request,
    Response,
    Event,
}

/// Exhaustive list of `type` values understood on the Canal_IPC.
///
/// Chat and lifecycle types use plain `snake_case`. Storage types use the
/// `storage.<op>` notation on the wire, matched by explicit `serde(rename)`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MessageType {
    // --- Lifecycle and chat ------------------------------------------------
    #[serde(rename = "user_message")]
    UserMessage,
    #[serde(rename = "agent_reply")]
    AgentReply,
    #[serde(rename = "agent_init")]
    AgentInit,
    #[serde(rename = "agent_init_ack")]
    AgentInitAck,
    #[serde(rename = "shutdown")]
    Shutdown,
    #[serde(rename = "agent_tool_progress")]
    AgentToolProgress,

    // --- Storage: tasks ----------------------------------------------------
    #[serde(rename = "storage.list_tasks")]
    StorageListTasks,
    #[serde(rename = "storage.create_task")]
    StorageCreateTask,
    #[serde(rename = "storage.update_task")]
    StorageUpdateTask,
    #[serde(rename = "storage.complete_task")]
    StorageCompleteTask,
    #[serde(rename = "storage.delete_task")]
    StorageDeleteTask,

    // --- Storage: events ---------------------------------------------------
    #[serde(rename = "storage.list_events")]
    StorageListEvents,
    #[serde(rename = "storage.create_event")]
    StorageCreateEvent,
    #[serde(rename = "storage.update_event")]
    StorageUpdateEvent,
    #[serde(rename = "storage.delete_event")]
    StorageDeleteEvent,

    // --- Storage: groups ---------------------------------------------------
    #[serde(rename = "storage.list_groups")]
    StorageListGroups,
    #[serde(rename = "storage.create_group")]
    StorageCreateGroup,
    #[serde(rename = "storage.rename_group")]
    StorageRenameGroup,
    #[serde(rename = "storage.recolor_group")]
    StorageRecolorGroup,
    #[serde(rename = "storage.delete_group")]
    StorageDeleteGroup,

    // --- Storage: export ---------------------------------------------------
    #[serde(rename = "storage.export_markdown")]
    StorageExportMarkdown,
    #[serde(rename = "storage.export_sqlite")]
    StorageExportSqlite,

    // --- Storage: sync ----------------------------------------------------
    #[serde(rename = "storage.sync_google")]
    StorageSyncGoogle,

    // --- Storage: notes ---------------------------------------------------
    #[serde(rename = "storage.list_notes")]
    StorageListNotes,
    #[serde(rename = "storage.search_notes")]
    StorageSearchNotes,
    #[serde(rename = "storage.create_note")]
    StorageCreateNote,
    #[serde(rename = "storage.update_note")]
    StorageUpdateNote,
    #[serde(rename = "storage.delete_note")]
    StorageDeleteNote,
}

// ---------------------------------------------------------------------------
// StorageError
// ---------------------------------------------------------------------------

/// Machine-readable storage error carried in `Envelope.error`.
///
/// Matches the wire shape `{ "code": "...", "message": "..." }`. The set
/// of canonical codes is documented in `design.md` → Error Handling and
/// is enforced by the storage crate in later tasks.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageError {
    pub code: String,
    pub message: String,
}

impl StorageError {
    pub fn new(code: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            code: code.into(),
            message: message.into(),
        }
    }
}

// ---------------------------------------------------------------------------
// Chat / lifecycle payloads
// ---------------------------------------------------------------------------

/// Payload of `user_message` (TUI → Agente).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UserMessagePayload {
    pub text: String,
}

/// Payload of `agent_reply` (Agente → TUI).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AgentReplyPayload {
    pub text: String,
}

/// Payload of `agent_init` (TUI → Agent).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AgentInitPayload {
    pub timezone: String,
    #[serde(default = "default_language")]
    pub language: String,
    pub model_provider: ModelProvider,
    /// Backend identifier: "ollama", "bedrock", "openai", "anthropic", "google", "llamaapi".
    pub backend: String,
    /// Model ID for the active backend.
    pub model_id: String,
    /// Host URL (only relevant for ollama).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
}

fn default_language() -> String {
    "en".to_string()
}

/// Origin of the language model the Agent is using.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ModelProvider {
    Local,
    Remote,
}

/// Payload of `agent_init_ack` (Agente → TUI).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AgentInitAckPayload {
    /// Optional human-readable notice shown in the chat log, for example
    /// when a remote model provider is in use (see Requisito 9.4).
    pub provider_notice: Option<String>,
}

/// Payload of `agent_tool_progress` (Agente → TUI, `kind = event`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AgentToolProgressPayload {
    pub tool: String,
    pub phase: ToolProgressPhase,
}

/// Start/end marker of an Agent tool invocation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ToolProgressPhase {
    Start,
    End,
}

/// Payload of `shutdown` (TUI → Agente). Carries no fields but is modelled
/// as a distinct type so it can be constructed and validated like the rest.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct ShutdownPayload {}

// ---------------------------------------------------------------------------
// Shared domain vocabulary used by storage payloads
// ---------------------------------------------------------------------------

/// Task priority, matching the Almacén CHECK constraint.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Priority {
    Alta,
    Media,
    Baja,
}

/// Task status, matching the Almacén CHECK constraint.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TaskStatus {
    Pendiente,
    Completada,
    Cancelada,
}

// ---------------------------------------------------------------------------
// Storage DTOs (Tasks, Events, Groups)
// ---------------------------------------------------------------------------

/// IPC-level representation of a Task. Dates are ISO 8601 strings so the
/// IPC layer does not depend on the `storage` crate yet.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageTaskDto {
    pub id: i64,
    pub title: String,
    pub priority: Priority,
    pub status: TaskStatus,
    /// ISO 8601 timestamp with timezone offset.
    pub created_at: String,
    /// ISO 8601 timestamp with timezone offset; `None` when the Task has
    /// no deadline.
    pub deadline: Option<String>,
    pub group_id: Option<i64>,
}

/// Patch used by `storage.update_task`. Any field left as `None` is not
/// modified. Nullable domain fields (deadline, group_id) use the
/// double-wrapped `Option<Option<T>>` pattern to distinguish "don't
/// touch" from "set to NULL".
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct StorageTaskPatch {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub priority: Option<Priority>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<TaskStatus>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<Option<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_id: Option<Option<i64>>,
}

/// IPC-level representation of an Event.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageEventDto {
    pub id: i64,
    pub title: String,
    /// `YYYY-MM-DD`.
    pub start_date: String,
    /// `HH:MM`.
    pub start_time: String,
    pub duration_minutes: Option<u32>,
    pub group_id: Option<i64>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct StorageEventPatch {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub start_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_minutes: Option<Option<u32>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_id: Option<Option<i64>>,
}

/// IPC-level representation of a Group.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageGroupDto {
    pub id: i64,
    pub name: String,
    /// Hex color code `#RRGGBB`.
    pub color: String,
}

// ---------------------------------------------------------------------------
// Storage.Tasks request/response payloads
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct StorageListTasksRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<TaskStatus>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_id: Option<Option<i64>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub to_date: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageListTasksResponse {
    pub tasks: Vec<StorageTaskDto>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageCreateTaskRequest {
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub priority: Option<Priority>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_id: Option<i64>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageCreateTaskResponse {
    pub task: StorageTaskDto,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageUpdateTaskRequest {
    pub id: i64,
    pub patch: StorageTaskPatch,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageUpdateTaskResponse {
    pub task: StorageTaskDto,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageCompleteTaskRequest {
    pub id: i64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageCompleteTaskResponse {
    pub task: StorageTaskDto,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageDeleteTaskRequest {
    pub id: i64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct StorageDeleteTaskResponse {}

// ---------------------------------------------------------------------------
// Storage.Events request/response payloads
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct StorageListEventsRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub to_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_id: Option<Option<i64>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageListEventsResponse {
    pub events: Vec<StorageEventDto>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageCreateEventRequest {
    pub title: String,
    pub start_date: String,
    pub start_time: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_minutes: Option<u32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_id: Option<i64>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageCreateEventResponse {
    pub event: StorageEventDto,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageUpdateEventRequest {
    pub id: i64,
    pub patch: StorageEventPatch,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageUpdateEventResponse {
    pub event: StorageEventDto,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageDeleteEventRequest {
    pub id: i64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct StorageDeleteEventResponse {}

// ---------------------------------------------------------------------------
// Storage.Groups request/response payloads
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct StorageListGroupsRequest {}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageListGroupsResponse {
    pub groups: Vec<StorageGroupDto>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageCreateGroupRequest {
    pub name: String,
    pub color: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageCreateGroupResponse {
    pub group: StorageGroupDto,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageRenameGroupRequest {
    pub id: i64,
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageRenameGroupResponse {
    pub group: StorageGroupDto,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageRecolorGroupRequest {
    pub id: i64,
    pub color: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageRecolorGroupResponse {
    pub group: StorageGroupDto,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageDeleteGroupRequest {
    pub id: i64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct StorageDeleteGroupResponse {}

// ---------------------------------------------------------------------------
// Storage.Export request/response payloads
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageExportMarkdownRequest {
    pub output_path: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageExportMarkdownResponse {
    pub written_path: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageExportSqliteRequest {
    pub output_path: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageExportSqliteResponse {
    pub written_path: String,
}

// ---------------------------------------------------------------------------
// Storage.Notes request/response payloads
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageNoteDto {
    pub id: i64,
    pub title: String,
    pub body: String,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct StorageNotePatch {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct StorageListNotesRequest {}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageListNotesResponse {
    pub notes: Vec<StorageNoteDto>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageSearchNotesRequest {
    pub query: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageSearchNotesResponse {
    pub notes: Vec<StorageNoteDto>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageCreateNoteRequest {
    pub title: String,
    #[serde(default)]
    pub body: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageCreateNoteResponse {
    pub note: StorageNoteDto,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageUpdateNoteRequest {
    pub id: i64,
    pub patch: StorageNotePatch,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageUpdateNoteResponse {
    pub note: StorageNoteDto,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StorageDeleteNoteRequest {
    pub id: i64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct StorageDeleteNoteResponse {}

// ---------------------------------------------------------------------------
// Tests — minimal smoke checks wiring the types together. The full
// property-based round-trip test lives in task 2.2.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn user_message_envelope_round_trips_through_json() {
        let payload = UserMessagePayload {
            text: "crea una tarea urgente para mañana".to_string(),
        };
        let envelope = Envelope::new(Kind::Request, MessageType::UserMessage, &payload)
            .expect("payload serializes");

        let json = serde_json::to_string(&envelope).expect("envelope serializes");
        let decoded: Envelope = serde_json::from_str(&json).expect("envelope deserializes");

        assert_eq!(decoded, envelope);
        assert_eq!(decoded.v, PROTOCOL_VERSION);
        assert_eq!(decoded.kind, Kind::Request);
        assert_eq!(decoded.message_type, MessageType::UserMessage);
        let decoded_payload = decoded
            .payload_as::<UserMessagePayload>()
            .expect("payload decodes")
            .expect("payload present");
        assert_eq!(decoded_payload, payload);
    }

    #[test]
    fn error_response_envelope_round_trips_without_payload() {
        let request_id = Uuid::new_v4();
        let envelope = Envelope::new_empty(Kind::Response, MessageType::StorageCreateGroup)
            .with_ref(request_id)
            .with_error(StorageError::new(
                "GROUP_NAME_NOT_UNIQUE",
                "Ya existe un Grupo llamado 'trabajo'",
            ));

        let json = serde_json::to_string(&envelope).expect("envelope serializes");
        let decoded: Envelope = serde_json::from_str(&json).expect("envelope deserializes");

        assert_eq!(decoded, envelope);
        assert!(decoded.payload.is_none());
        assert_eq!(decoded.ref_id, Some(request_id));
        assert_eq!(decoded.error.as_ref().unwrap().code, "GROUP_NAME_NOT_UNIQUE");
    }

    #[test]
    fn storage_task_type_serializes_with_dotted_notation() {
        let mt = MessageType::StorageCreateTask;
        let json = serde_json::to_string(&mt).expect("type serializes");
        assert_eq!(json, "\"storage.create_task\"");
    }

    #[test]
    fn unsupported_protocol_version_fails_to_deserialize() {
        let raw = serde_json::json!({
            "v": 2,
            "id": "00000000-0000-4000-8000-000000000000",
            "kind": "request",
            "type": "user_message",
            "payload": { "text": "hola" }
        });

        let result: Result<Envelope, _> = serde_json::from_value(raw);
        let err = result.expect_err("v=2 must be rejected");
        let message = err.to_string();
        assert!(
            message.contains("unsupported IPC protocol version"),
            "unexpected error message: {message}"
        );
    }

    #[test]
    fn model_provider_serializes_lowercase() {
        let json = serde_json::to_string(&ModelProvider::Remote).expect("serializes");
        assert_eq!(json, "\"remote\"");
    }

    #[test]
    fn priority_serializes_in_spanish() {
        let json = serde_json::to_string(&Priority::Alta).expect("serializes");
        assert_eq!(json, "\"alta\"");
    }

    #[test]
    fn task_status_serializes_in_spanish() {
        let json = serde_json::to_string(&TaskStatus::Pendiente).expect("serializes");
        assert_eq!(json, "\"pendiente\"");
    }

    #[test]
    fn storage_task_dto_round_trips() {
        let dto = StorageTaskDto {
            id: 42,
            title: "Comprar pan".to_string(),
            priority: Priority::Alta,
            status: TaskStatus::Pendiente,
            created_at: "2025-02-14T10:12:00+01:00".to_string(),
            deadline: Some("2025-02-15T09:00:00+01:00".to_string()),
            group_id: Some(3),
        };
        let json = serde_json::to_string(&dto).expect("dto serializes");
        let decoded: StorageTaskDto = serde_json::from_str(&json).expect("dto deserializes");
        assert_eq!(dto, decoded);
    }
}
